* Historie

** Kongerekka

*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       f55a7fe3-c5f4-4fdd-a188-33ddcd003de6
:END:
Kong [Harald 1 Halfdansson Hårfagre] regjerte fra ca [865] til ca [931] 
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       ce1f1834-36e5-4831-b515-13c4cac9e785
:END:
Kong [Eirik 1 Haraldsson Blodøks] regjerte fra ca [931] til ca [933] 
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       08730969-2a2b-4f2c-9be8-1c470aab98c0
:END:
Kong [Håkon 1 Haraldsson Adelstensfostre – den gode] regjerte fra ca [933] til ca [960] 
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       ae11d7d2-78b1-4602-94b7-f4882a16d08b
:END:
Kong [Harald 2 Eriksson Gråfell] regjerte fra ca [960] til ca [970] 
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       d96e49a5-3c79-47f3-a3e8-cb37ed173f97
:END:
Kong [Håkon Sigurdsson Ladejarl dansk styre] regjerte fra ca [970] til [995].

Han vant i slaget ved [Hjørungavåg|nordøst på Hareidlandet] (muligens i [986]), og ble drept av [Kark|på Rimul].

Han var gift med [Tora Skagesdatter]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       2c13c568-fe32-4cde-b568-82ae4501c896
:END:
Kong [Olav 1 Tryggvason] regjerte fra [995] til [1000].

Han falt i slaget ved [Svolder] i [999 eller 1000].
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       f00a9387-0eb4-4f9e-8178-e882f4f477d7
:END:
Kong [Eirik og Svein Håkonsson Ladejarler dansk styre] regjerte fra [1000] til [1015] 
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       3f9a7e56-39ee-4b09-ae35-f9333006a4c5
:END:
Kong [Olav 2 Haraldsson den Hellige] regjerte fra [1015] til [1028] 
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       f2c7887d-fd47-4f5e-8b64-3e43d0f1594c
:END:
Kong [Håkon Eiriksson Ladejarl dansk styre] regjerte fra [1028] til [1029].

Han var sønn av [Gyda Sveinsdatter|Tjueskjegg]. Døde som følge av [drukning]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       7a78120f-a012-49ad-a38a-20509991b59c
:END:
Kong [Knud Sveinsson den store / den mektige] regjerte fra [1029] til [1030].

Sønn av [Svein Tjueskjegg], som igjen var sønn av [Harald Blåtann], som igjen var sønn av [Gorm den gamle]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       c95771c0-48c0-4439-b1bc-6085ac5f529b
:END:
Kong [Svein Knutsson Alfivason dansk styre] regjerte fra 1030 til 1035.

Sønn av [Knud den store]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       62ce953b-7d3b-4558-bc7d-f4d12f181d3c
:END:
Kong [Magnus 1 Olavsson den gode] regjerte fra [1035] til [1047].

Sønn av [Olav den Hellige]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       c5a7cf77-66b7-407f-a1d6-7b27fbe6437b
:END:
Kong [Harald 3 Sigurdsson Hardråde] regjerte fra [1045] til [1066]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       8f62817b-119f-4f98-9505-10bac5642394
:END:
Kong [Magnus 2 Haraldsson] regjerte fra [1066] til [1069]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       315f3523-4de7-4bab-9eff-75aac51179e6
:END:
Kong [Olav 3 Haraldsson Kyrre] regjerte fra [1067] til [1093]
*** Konge :drill:
SCHEDULED: <2024-08-17 lø.>
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       99622433-54d7-488a-a0e8-d025e096103e
:DRILL_LAST_INTERVAL: 3.86
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 1
:DRILL_AVERAGE_QUALITY: 2.0
:DRILL_EASE: 2.36
:DRILL_LAST_QUALITY: 3
:DRILL_LAST_REVIEWED: [2024-08-13 ti. 16:58]
:END:
Kong [Håkon Magnusson Toresfostre|16. Han fikk ikke nummer etter navn] regjerte fra [1093] til [1095].

Sønn av [Magnus 2]
**** Memo
Severdighet på Slottet: Haakon blotter seg på kongedassen
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       5d52fd66-2ad3-4b62-b6d1-bebbfd242456
:END:
Kong [Magnus 3 Olavsson Berrføtt] regjerte fra [1093] til [1103]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       e5ed843d-1246-48ab-927f-7da4a925dcac
:END:
Kong [Olav Magnusson] regjerte fra [1103] til [1115].

Han døde 16 år gammel, for ung til offisiell konge.
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       eb068919-9ac1-4f3e-ae92-49ae40342b53
:END:
Kong [Øystein 1 Magnusson] regjerte fra [1103] til [1123]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       cd6ca29b-b24e-4bef-82c2-65422ce944ec
:END:
Kong [Sigurd 1 Magnusson Jorsalfare] regjerte fra [1103] til [1130]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       f2dc530f-5f72-45fa-b1f4-8cbbdf9a49bb
:END:
Kong [Magnus 4 Sigurdsson den blinde] regjerte fra [1130] til [1135].

Han tapte slaget ved [Minne], og falt ved slaget ved [Holmengrå]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       cc0ac5bb-d8f1-4017-b64c-e4a15618ac2a
:END:
Kong [Harald 4 Magnusson Gille] regjerte fra [1130] til [1136]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       3348c78e-61ae-4c0d-9ded-a51f421f279b
:END:
Kong [Sigurd 2 Haraldsson Munn] regjerte fra [1136] til [1155]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       cd34f0ad-dd54-44b1-b891-e755d6e99514
:END:
Kong [Inge 1 Haraldsson Krokrygg] regjerte fra [1136] til [1161]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       7fffc696-a58c-4c8a-afc8-f729d45bb83e
:END:
Kong [Øystein 2 Haraldsson] regjerte fra [1142] til [1157]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       cef013fe-7dac-4e73-b3fa-0752ee527d86
:END:
Kong [Håkon 2 Sigurdsson Herdebrei] regjerte fra [1157] til [1162].

Falt i slaget på [Sekken]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       ef399dfb-ed0c-4852-9d05-c57edeca16d0
:END:
Kong [Magnus 5 Erlingsson] regjerte fra [1161] til [1184].

Sønn av [Skakke|Kalvskinnet]. Falt ved slaget på [Fimreite]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       b34fb133-c5c3-4ee3-afa2-c3d3ada8a28c
:END:
Kong [Sverre Sigurdsson] regjerte fra [1177] til [1202]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       5aa420b7-9420-4c4f-9bb9-b8040cbd9132
:END:
Kong [Håkon 3 Sverresson] regjerte fra [1202] til [1204]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       b6c61acf-c1d7-44d6-bd6f-d204ffc0c883
:END:
Kong [Inge 2 Bårdsson] regjerte fra [1204] til [1217].

Datter av [Cecilia|Sigurdsdatter], [Sverre]s søster. Halvbror til [Hertug Skule]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       02b6094f-5458-48d5-adf7-c87628de089c
:END:
Kong [Håkon 4 Håkonsson] regjerte fra [1217] til [1263]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       e009c870-15e9-4d7e-83eb-0a8f62fdbe74
:DRILL_LAST_INTERVAL: 0.0
:DRILL_REPEATS_SINCE_FAIL: 1
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 2
:DRILL_AVERAGE_QUALITY: 1.5
:DRILL_EASE: 2.5
:DRILL_LAST_QUALITY: 2
:DRILL_LAST_REVIEWED: [2024-08-13 ti. 17:56]
:END:
Kong [Magnus 6 Håkonsson Lagabøte|32] regjerte fra [1263] til [1280]
**** Memo
Gardist Pål Magnus har satt seg på en ELEFANT:
Han bærer kongens FLOSSHATT (som han har stjålet),
og med BALLONG i hånden (i stedet for gevær over skulderen)
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       a851610e-013c-41e1-925f-678caba4dd25
:END:
Kong [Eirik 2 Magnusson] regjerte fra [1280] til [1299]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       664c29de-be44-4c80-88d0-f4e323ddf322
:END:
Kong [Håkon 5 Magnusson] regjerte fra [1299] til [1319]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       77d3f4c2-5de1-48ab-8b70-42c523494728
:END:
Kong [Magnus 7 Eriksson] regjerte fra [1319] til [1355]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       3ebd5d41-a984-4f15-a5e5-5c597a9f38ef
:END:
Kong [Håkon 6 Magnusson] regjerte fra [1343] til [1380]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       dfe2f894-8dd2-4c64-a93c-8031376071b6
:END:
Kong [Olav 4 Håkonsson] regjerte fra [1380] til [1387]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       5a295ad7-84e0-45d9-aab7-f374d9535181
:END:
Kong [Margrete Valdemarsdatter] regjerte fra [1388] til [1412].

Datter av [Atterdag]. Førte krigen mot [Albrekt av Mecklenburg] (1388-1395)
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       4ddebcbe-e692-4130-98f6-8bb91d12f175
:END:
Kong [Eirik 3 Erik av Pommern] regjerte fra [1389] til [1442].

Førte krigen om [Slesvig] (1416-1432)
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       73592d3b-e1cd-483e-9d90-b7c599cfa291
:END:
Kong [Christoffer av Bayern] regjerte fra [1442] til [1448]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       3beef949-671c-4574-9fc9-76eace273729
:END:
Kong [Carl 1 Knutsson Bonde] regjerte fra [1449] til [1450]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       e22ed935-2eab-4213-83ca-5844de066ec1
:END:
Kong [Christian 1] regjerte fra [1450] til [1481]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       9d4141be-6fef-4841-b74b-98b01b0cedec
:END:
Kong [Interregnum 1] regjerte fra [1481] til [1483]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       5cf814f1-3a43-4671-8da3-9bdd28816426
:END:
Kong [Hans] regjerte fra [1483] til [1513]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       2cfb3f0f-5976-4fe1-b576-bf61c366c87e
:END:
Kong [Christian 2] regjerte fra [1513] til [1523]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       7dd329bb-da95-4d59-a02a-504feb043644
:END:
Kong [Frederik 1] regjerte fra [1523] til [1533]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       e81f5de5-8b22-4c1a-84e7-edbd57a75bb1
:END:
Kong [Interregnum 2] regjerte fra [1533] til [1537]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       08438bae-9ae4-499d-96fb-15f2e72b1077
:END:
Kong [Christian 3] regjerte fra [1537] til [1559]
**** Memo
Christian Thorn på slottstrappen: med glanspapirhjerte og maske og klar for slottsball
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       63c29d3d-1c28-4b68-bc9a-4bb04459d3e9
:END:
Kong [Frederik 2] regjerte fra [1559] til [1588]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       9af7ac14-2f5d-4e6b-9836-c30040da6f1a
:END:
Kong [Christian 4] regjerte fra [1588] til [1648].

Tapte [Hannibalfeiden] som startet i [1643] og som endte med Freden i [Brömsebro] i [1645]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       efde6a14-c848-457b-9f1d-e68abddb2a9a
:END:
Kong [Frederik 3] regjerte fra [1648] til [1670].

Tapte [Karl X Gustavs første danske krig] fra [1647], som endte med Freden i [Roskilde] i [1658].

Vant [Bjelkefeiden] fra [1658] som etter den svenske kongens død raskt ende med freden i [Halden] i [1660]. Da ga Sverige tilbake [Trondhjems len og Enningdalen].

Krigshandlingene ved norskegrensen i disse to krigen kalles på norsk [Krabbefeiden]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       2b7a16f2-6ed5-49a7-bd8f-95b06060df92
:END:
Kong [Christian 5] regjerte fra [1670] til [1699]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       b8a51616-35e0-4f4a-a8b1-e745c3231927
:END:
Kong [Frederik 4] regjerte fra [1699] til [1730]
**** Memo
Christian Thorn på slottstrappen: sitter på en elefant og prøver hjelpeløst å kvele den med en klesklype
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       8686ac1e-d842-4fd2-953d-f1116b3ad262
:END:
Kong [Christian 6] regjerte fra [1730] til [1746]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       1929b0dc-9308-431b-bd69-2029b91b1d9f
:END:
Kong [Frederik 5] regjerte fra [1746] til [1766]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       e1b37074-4fbc-4f5a-b143-b6c8c6aa10d8
:END:
Kong [Christian 7] regjerte fra [1766] til [1808].

Førte den «meningsløse» [Tyttebærkrigen] i årene [1788-1789]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       5f30b32a-3d5a-4d88-a1dd-9c6b442ee30d
:END:
Kong [Frederik 6] regjerte fra [1808] til [1814]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       b446d41f-ae83-4b09-ae9b-c84b0e7ce173
:END:
Kong [Christian Frederik] regjerte fra [1814] til [1814]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       d0e07451-0be4-401a-89f8-199a59220ee2
:END:
Kong [Carl 2] regjerte fra [1814] til [1818]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       e9353541-4031-4f99-8ef4-7a57c617aeaa
:END:
Kong [Carl 3 Johan] regjerte fra [1818] til [1844]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       87dd1911-9617-4f0e-ba33-9d4ab505b202
:END:
Kong [Oscar 1] regjerte fra [1844] til [1859]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       33b06c52-e56e-4b2c-874e-28e378d6b0c6
:END:
Kong [Carl 4] regjerte fra [1859] til [1872]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       c6e9bade-f265-44c0-99ab-2d03b7f96780
:END:
Kong [Oscar 2] regjerte fra [1872] til [1905]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       9f0aba19-bffe-4ee9-98ad-afc2eecf4cb6
:END:
Kong [Haakon 7] regjerte fra [1905] til [1957]
*** Konge :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:ID:       380c14f2-c40e-4e66-b220-8e2a105e10f4
:END:
Kong [Olav 5] regjerte fra [1957] til [1991]
