* Film

** Ridley Scott

*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Sir Ridley Scott fra [South Shields], [Tyne and Wear], ble født i [1937]. Fra 2015 er han gift med [Giannina Facio].

Han har tre sønner, [Jake], [Luke] og [Jordan].

Hans regissørbror, Tony, er født i [1944].
**** Memo
Han steg opp av Tyne som baby med en glorie.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
The [Duellists] er Ridley Scotts debutfilm fra [1977] med [Harvey Keitel],
[Keith Carradine] og [Albert Finney] i hovedrollene.

Handlingen er lagt til [Napoleonskrigene].

Filmen is based on [Joseph Conrad]'s short story ["The Duel"] (titled
"Point of Honor" in the United States), first published in A Set of
Six.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
[Alien] er fra [1979].

The film stars [Tom Skerritt], Sigourney Weaver, [Veronica Cartwright],
[Harry Dean Stanton], [John Hurt], Ian Holm, and [Yaphet Kotto].

Screenplay by [Dan O'Bannon].
**** Memo
Steve Bannon skrev Alien for Breitbart.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
[Blade Runner] fra [1982]. Starring [Harrison Ford], [Rutger Hauer],
[Sean Young], and [Edward James Olmos], it is an adaptation of [Philip
K. Dick]'s [1968] novel [Do Androids Dream of Electric Sheep]?

Music by Vangelis
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
[Legend] is a [1985] American film directed by Ridley Scott, written
by [William Hjortsberg], and starring [Tom Cruise], [Mia Sara], [Tim
Curry].

Music by [Tangerine Dream] (US version)
[Jerry Goldsmith] (European version and director's cut)
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
[Someone to Watch Over Me] is a [1987] American neo-noir romantic thriller
film directed by Ridley Scott and written by [Howard Franklin]. It stars
[Tom Berenger] as a police detective who has to protect a wealthy woman
([Mimi Rogers]), who is a key witness in a murder trial. The film's
soundtrack includes the [George] and [Ira Gershwin] song from which the
film takes its title, recorded by [Sting], and [Vangelis]' "[Memories of
Green]", originally from Scott's [Blade Runner].

Rotten Tomatoes 65% rating based on 31 reviews
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
[Black Rain] is a [1989] American neo-noir crime thriller film
directed by Ridley Scott and starring [Michael Douglas], [Andy
García], Ken Takakura, [Kate Capshaw]. The film focuses on two NYPD
detectives who arrest a member of the yakuza and must escort him back
to Japan. Once there, he escapes and the two officers find themselves
dragged deeper and deeper into the Japanese underworld.

Music by [Hans Zimmer] (!)

Rotten Tomatoes 86% rating based on 147 reviews
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
[Thelma & Louise] is a [1991] American crime drama film directed by Ridley
Scott and written by [Callie Khouri]. The film stars Susan Sarandon and
Geena Davis as Louise and Thelma, two friends who embark on a road
trip that ends up in unforeseen circumstances. The supporting cast
includes [Harvey Keitel], [Michael Madsen], Christopher McDonald, and Brad
Pitt (in one of his first major roles).

Music by [Hans Zimmer]

Rotten Tomatoes 86% rating based on 147 reviews
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
[1492: Conquest of Paradise] is a [1992] epic historical drama film
directed and produced by Ridley Scott, written by [Roselyne Bosch] and
starring [Gérard Depardieu], [Fernando Rey] (Charnier!), [Michael Wincott], and
[Sigourney Weaver].

Music by [Vangelis]

Rotten Tomatoes 32% rating based on 22 reviews
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
[White Squall] is a 1996 American disaster survival film directed by
Ridley Scott. It is a coming of age film in which a group of high
school and college-aged teenagers sign up for several months of
training aboard a sailing ship, a brigantine, and travel around half
the globe when suddenly they are challenged by a severe storm. The
film stars Jeff Bridges, Caroline Goodall, John Savage, Scott Wolf,
Jeremy Sisto and Balthazar Getty.

The film was based on the 1962 book The Last Voyage of the Albatross
by Charles Gieg Jr. and Felix Sutton.

Rotten Tomatoes: 57% based on 37 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
G.I. Jane is a 1997 American action drama film directed by Ridley
Scott and starring Demi Moore, Viggo Mortensen, and Anne Bancroft. The
film tells the fictional story of the first woman to undergo special
operations training similar to the U.S. Navy SEALs.

Music by Trevor Jones

Rotten Tomatoes: 53% based on 38 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Gladiator is a 2000 historical epic film directed by Ridley Scott
based on a story by David Franzoni. It stars Russell Crowe, Joaquin
Phoenix, Connie Nielsen, Oliver Reed, Derek Jacobi, Djimon Hounsou,
and Richard Harris.

Music by Hans Zimmer and Lisa Gerrard

Rotten Tomatoes: 80% based on 257 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Hannibal is a 2001 American horror film directed by Ridley Scott and
based on the 1999 novel by Thomas Harris. A sequel to the 1991 film
The Silence of the Lambs, the plot follows disgraced FBI special agent
Clarice Starling as she attempts to apprehend cannibalistic serial
killer Hannibal Lecter before his surviving victim, Mason Verger,
captures him. Anthony Hopkins reprises his role as Lecter, while
Julianne Moore replaces Jodie Foster as Starling and Gary Oldman plays
Verger. Ray Liotta, Giancarlo Giannini, and Francesca Neri also star.
It’s an international co-production film between the United States and
the United Kingdom.

Music by Hans Zimmer

Rotten Tomatoes: 39% based on 172 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Black Hawk Down is a 2001 war film directed and produced by Ridley
Scott, and co-produced by Jerry Bruckheimer. It is based on the 1999
eponymous non-fiction book by journalist Mark Bowden, about the crew
of a Black Hawk helicopter that was shot down during the Battle of
Mogadishu. The film features a large ensemble cast, including Josh
Hartnett, Ewan McGregor, Eric Bana, Tom Sizemore, William Fichtner,
Jason Isaacs, Sam Shepard, Jeremy Piven, Ioan Gruffudd, Ewen Bremner,
Hugh Dancy, and Tom Hardy in his first film role. Orlando Bloom, Ty
Burrell, and Nikolaj Coster-Waldau also have minor roles.

Music by Hans Zimmer

Rotten Tomatoes: 77% based on 175 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Matchstick Men is a 2003 black comedy crime film directed by Ridley
Scott and based on Eric Garcia's 2002 novel of the same name. The film
stars Nicolas Cage, Sam Rockwell, Bruce McGill, and Alison Lohman. The
film.

Roy Waller is a con artist from Los Angeles with severe Tourette
syndrome and obsessive-compulsive disorder.

Music by Hans Zimmer

Rotten Tomatoes: 82% based on 186 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Kingdom of Heaven is a 2005 epic historical drama film directed and
produced by Ridley Scott and written by William Monahan. It features
an ensemble cast including Orlando Bloom, Eva Green, Jeremy Irons,
David Thewlis, Brendan Gleeson, Marton Csokas, and Liam Neeson.

The film is a heavily fictionalised portrayal of the events leading to
the Third Crusade, focusing mainly on Balian of Ibelin who fights to
defend the Crusader Kingdom of Jerusalem from the Ayyubid Sultan
Saladin.

Music by Harry Gregson-Williams

Rotten Tomatoes: 40% based on 189 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
A Good Year is a 2006 romantic comedy-drama film directed and produced
by Ridley Scott. The film stars Russell Crowe, Marion Cotillard,
Didier Bourdon, Abbie Cornish, Tom Hollander, Freddie Highmore and
Albert Finney. The film is based on the 2004 novel of the same name by
British author Peter Mayle.

Young Max Skinner, whose parents died in an accident, spends his
childhood summer holidays learning to appreciate the finer things at
his Uncle Henry's vineyard estate in Provence in southeastern France.
Twenty-five years later, Max is a successful but arrogant workaholic
trader in London with a cheeky-chappy persona.

Music by Marc Streitenfeld

Rotten Tomatoes: 26% based on 134 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
American Gangster is a 2007 American biographical crime film directed
and produced by Ridley Scott and written by Steven Zaillian. The film
is loosely based on the criminal career of Frank Lucas, a gangster
from La Grange, North Carolina who smuggled heroin into the United
States on American service planes returning from the Vietnam War,
before being detained by a task force led by Newark Detective Richie
Roberts. The film stars Denzel Washington and Russell Crowe, with
co-stars Ted Levine, John Ortiz, Josh Brolin, Chiwetel Ejiofor, Ruby
Dee, Lymari Nadal and Cuba Gooding Jr.

Music by Marc Streitenfeld

Rotten Tomatoes: 81% based on 218 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Body of Lies is a 2008 American spy action thriller film[3] directed
and produced by Ridley Scott, written by William Monahan, and starring
Leonardo DiCaprio, Russell Crowe and Golshifteh Farahani in the lead
roles. Set in the Middle East, it follows the attempts of the CIA and
the GID of Jordan to catch "al-Saleem", a terrorist. Frustrated by
their target's elusiveness, differences in their approaches strain
relations between a CIA operative, his superior, and the head of
Jordanian Intelligence. The supporting cast features Mark Strong and
Oscar Isaac.

Music by Marc Streitenfeld

Rotten Tomatoes: 55% based on 216 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Robin Hood is a 2010 historical action-adventure film based on the
Robin Hood legend, directed by Ridley Scott and starring Russell
Crowe, Cate Blanchett, William Hurt, Mark Strong, Mark Addy, Oscar
Isaac, Danny Huston, Eileen Atkins, and Max von Sydow.

Screenplay by Brian Helgeland

Music by Marc Streitenfeld

Rotten Tomatoes: 43% based on 251 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Prometheus is a 2012 science fiction horror film directed by Ridley
Scott and written by Jon Spaihts and Damon Lindelof. It is the fifth
installment of the Alien film series and features an ensemble cast
including Noomi Rapace, Michael Fassbender, Guy Pearce, Idris Elba,
Logan Marshall-Green, and Charlize Theron. Set in the late 21st
century, the film centers on the crew of the spaceship Prometheus as
it follows a star map discovered among the artifacts of several
ancient Earth cultures. Seeking the origins of humanity, the crew
arrives on a distant world and discovers a threat that could cause the
extinction of the human species.

Written by Jon Spaihts and Damon Lindelof

Music by Marc Streitenfeld

Rotten Tomatoes: 73% based on 312 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
The Counselor (known as The Counsellor in countries that use British
English) is a 2013 crime thriller film directed by Ridley Scott and
written by Cormac McCarthy. It stars Michael Fassbender as the
eponymous Counselor as well as Penélope Cruz, Cameron Diaz, Javier
Bardem, and Brad Pitt. The film deals with themes such as greed,
mortality, love, and trust in the context of the Mexican drug trade.
The extremely violent and bloodthirsty activities of drug cartels are
depicted as the Counselor, a high-level lawyer, gets involved in a
drug deal around the troubled Ciudad Juarez, Mexico/Texas border area.

Music by Daniel Pemberton

Rotten Tomatoes: 34% based on 221 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Exodus: Gods and Kings is a 2014 biblical epic film directed and
produced by Ridley Scott, and written by Adam Cooper, Bill Collage,
Jeffrey Caine, and Steven Zaillian. The film stars Christian Bale,
Joel Edgerton, John Turturro, Aaron Paul, Ben Mendelsohn, Sigourney
Weaver, and Ben Kingsley. It is inspired by the biblical episode of
the Exodus of the Hebrews from Egypt led by Moses and related in the
Book of Exodus. Development on the film was first announced by Scott
in June 2012. Filming occurred primarily in Spain beginning in October
2013, with additional filming at Pinewood Studios in England.

Music by Alberto Iglesias

Rotten Tomatoes: 30% based on 210 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
The Martian is a 2015 science fiction film directed by Ridley Scott
and starring Matt Damon. Drew Goddard adapted the screenplay from the
2011 novel by Andy Weir. It also stars Jessica Chastain, Jeff Daniels,
Kristen Wiig, Chiwetel Ejiofor, Sean Bean, Michael Peña, Kate Mara,
Sebastian Stan, Aksel Hennie, Mackenzie Davis, Donald Glover, and
Benedict Wong. The film depicts an astronaut's struggle to survive on
Mars after being left behind and NASA's efforts to return him to
Earth.

Music by Harry Gregson-Williams

Rotten Tomatoes: 91% based on 383 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Alien: Covenant is a 2017 science fiction horror film directed and
produced by Ridley Scott, and written by John Logan and Dante Harper
from a story by Michael Green and Jack Paglen. A joint American and
British production, it is part of the Alien franchise, serving as a
sequel to Prometheus (2012). It features returning star Michael
Fassbender, with Katherine Waterston, Billy Crudup, Danny McBride, and
Demián Bichir in supporting roles. It follows the crew of a colony
ship that lands on an uncharted planet and makes a terrifying
discovery.

Music by Jed Kurzel

Rotten Tomatoes: 65% based on 408 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
All the Money in the World is a 2017 biographical crime thriller film
directed by Ridley Scott and written by David Scarpa. Based on John
Pearson's 1995 book Painfully Rich: The Outrageous Fortunes and
Misfortunes of the Heirs of J. Paul Getty, it depicts the events
surrounding the 1973 kidnapping of John Paul Getty III and the refusal
of his grandfather, the multi-billionaire oil tycoon J. Paul Getty, to
cooperate with the kidnappers' extortion demands. The film stars
Michelle Williams as Gail Harris Getty, John Paul Getty III's mother,
Christopher Plummer as Getty, and Mark Wahlberg as Fletcher Chace, an
adviser of the Getty family.

Music by Daniel Pemberton

Rotten Tomatoes: 79% based on 262 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
The Last Duel is a 2021 historical drama film[6] directed by Ridley
Scott from a screenplay by Nicole Holofcener, Ben Affleck, and Matt
Damon, based on the 2004 book The Last Duel: A True Story of Crime,
Scandal, and Trial by Combat in Medieval France by Eric Jager. Set in
medieval France, the film stars Damon as Jean de Carrouges, a knight
who challenges his former friend, squire Jacques le Gris (Adam
Driver), to a judicial duel after Jean's wife, Marguerite (Jodie
Comer), accuses Jacques of raping her. The events leading up to the
duel are divided into three distinct chapters, reflecting the
contradictory perspectives of the three main characters. Affleck also
stars in a supporting role as Count Pierre d'Alençon.

Music by Harry Gregson-Williams

Rotten Tomatoes: 85% based on 287 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
House of Gucci is a 2021 American biographical crime drama film
directed by Ridley Scott, based on the 2001 book The House of Gucci: A
Sensational Story of Murder, Madness, Glamour, and Greed by Sara Gay
Forden. The film follows Patrizia Reggiani (Lady Gaga) and Maurizio
Gucci (Adam Driver), as their romance transforms into a fight for
control of the Italian fashion brand Gucci. Jared Leto, Jeremy Irons,
Jack Huston, Salma Hayek, and Al Pacino also star.

Music by Harry Gregson-Williams

Rotten Tomatoes: 62% based on 373 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Napoleon is a 2023 epic biographical war film directed and produced by
Ridley Scott, and written by David Scarpa. Based on the life of
Napoleon and primarily depicting his rise to power as well as his
relationship with his wife, Joséphine, it stars Joaquin Phoenix as
Napoleon and Vanessa Kirby as Joséphine.

Music by Martin Phipps

Rotten Tomatoes: 62% based on 373 reviews.
*** Ridley Scott :drill:
:PROPERTIES:
:DRILL_CARD_TYPE: hide2cloze
:END:
Gladiator II is a 2024 epic historical action film directed and
produced by Ridley Scott that serves as a sequel to Gladiator (2000).
Written by David Scarpa, from a story he wrote with Peter Craig, the
film was produced by Scott Free Productions and distributed by
Paramount Pictures. It stars Paul Mescal, Pedro Pascal, Joseph Quinn,
Fred Hechinger, Lior Raz, Derek Jacobi, Connie Nielsen, and Denzel
Washington.[6] Jacobi and Nielsen reprise their roles from the first
film, with Mescal replacing Spencer Treat Clark. Mescal portrays
Lucius, whose home is invaded by the Roman army led by General
Acacius. He seeks revenge against Acacius and fights as a gladiator
for Macrinus, a former slave who plans to overthrow the emperors Geta
and Caracalla.

Music by Harry Gregson-Williams

Rotten Tomatoes: 72% based on 292 reviews.


