(require 'cc-mode)
(require 'c++-insert)
(require 'c++-utils)
(require 'c++-file-templates)
(require 'c++-include)
(require 'c++-functor)
(require 'c++-compile)
(require 'c++-buffer)
(require 'c++-debug)
(require 'c++-method)

(define-key c++-mode-map "\C-cc" 'mb-make)
;; map for additions
(setq c++-mode-insert-map (make-sparse-keymap "Insert"))
(define-key c++-mode-map "\C-ci" c++-mode-insert-map)
(define-key c++-mode-insert-map "c" 'c++-insert-c-file-template)
(define-key c++-mode-insert-map "h" 'c++-insert-h-file-template)
(define-key c++-mode-insert-map "g" 'c++-insert-generator)
(define-key c++-mode-insert-map "u" 'c++-insert-unary-function)
(define-key c++-mode-insert-map "b" 'c++-insert-binary-function)
(define-key c++-mode-insert-map "i" 'c++-insert-include)
(define-key c++-mode-insert-map "k" 'c++-insert-class-def)
(define-key c++-mode-insert-map "e" 'c++-insert-cout-expression)
(define-key c++-mode-insert-map "G" 'c++-insert-get-method)
(define-key c++-mode-insert-map "s" 'c++-insert-set-method)
(define-key c++-mode-insert-map "m" 'c++-insert-method)
(define-key c++-mode-map [(meta \()] 'c++-insert-parentheses)
(define-key c++-mode-map [(f11)] #'(lambda (beg end) (interactive "r") (c++-std-ify-region 5)))

(provide 'c++-map)
