(("I hvilket år (f. Kr) ble Roma grunnlagt?" "753")
 ("Håndtere ulikt" "Forskjellsbehandle")
 ("Tegnefilm" "Animasjonsfilm")
 ("Salg under hammeren" "Auksjon")
 ("Innbilning" "Illusjon")
 ("Tenke nøye" "Konsentrasjon")
 ("Vann som pipler ut" "Lekkasje")
 ("Ganging i matte" "Multiplikasjon")
 ("Nurse that works during an operation" "Operasjonssykepleier")
 ("Viktig reise" "Ekspedisjon")
 ("Liten pakke" "Porsjonspakning"))

(("I hvilket år (f. Kr) ble Roma grunnlagt?" "753")
 ("Hvem drepte tvillingbroren sin og ble første konge av Roma?" "Romulus")
 ("Hva het den tvillingbroren til Romulus?" "Remus")
 ("Hva het den store romerske diktatoren som regjerte Roma fra 49 f.Kr. til 44 f.Kr.?" "Caesar")
 ("Hva het den første keiseren av romerriket (27 f.Kr. -- 14 e.Kr.)?" "Augustus")
 ("Hva het den andre keiseren av romerriket (14 -- 37) og som etterfulgte Augustus?" "Tiberius")
 ("Hva het den nærmest gale keieren (37 -- 41) som etterfulgte keiser Tiberius?" "Caligula")
 ("Hva het den fjerde keiseren av romerriket (41 -- 54)" "Claudius")
 ("Hva het den femte keiseren av romerriket (54 -- 68), som mange mener var enda galere enn Caligula?" "Nero")
 ("I hvilket år var rommeriket på sitt største i areal?" "117")
 ("Hvem var keiser da rommeriket var på sitt største i areal?" "Trajan")
 ("Hva heter den store gladiatorkampstadion i det gamle Roma, og som kunne ta opp mot 80 000 tilskuere? (Hint: har samme navn som en kino)" "Colosseum")
 ("Hva het den enorme hippodromen (hesteløpstadion) i det gamle Roma, med plass til over 150 000 tilskuere?" "Circus Maximus")
 ("Hvem skrev det romerske nasjonaldiktet «Aeniden»" "Vergil")
 ("Hva kalte romerne dagens Frankrike (pluss litt til som for eksempel Belgia)" "Gallia")
 ("Hva heter vulkanen som ødela byene Pompeii og Herculaneum" "Vesuv")
 ("I hvilket år ødela Vesuv byene Pompeii og Herculaneum" "73")
 ("Hva heter den øverste guden i romersk mytologi" "Zeus")
 ("Hva heter krigsguden i romersk mytologi" "Mars")
 ("Hva heter kjærlighetens gudinne i romersk mytologi" "Venus")
 ("Hva heter dødsrikets gud i romersk mytologi" "Pluto")
 ("Hva heter havets gud i romersk mytologi" "Neptun")
 ("Hva het den store retoren (taleren) som ble født i 106 f. Kr. og ble myrdet i 43" "Cicero"))

(("bestemme seg for" "set one's mind to")
 ("redskaper" "tools")
 ("gresstrå" "blade of grass")
 ("termitt" "termite")
 ("maur" "ant")
 ("mild" "gentle")
 ("(han) mister" "loses")
 ("tilholdssted" "habitat")
 ("krypskyttere" "poachers")
 ("bevissthet" "awareness")
 ("lære opp" "educate")
 ("samfunnet" "the public"))

(("(han) overlever" "survives")
 ("prest" "priest")
 ("reise (lang)" "voyage")
 ("reise (kort)" "journey")
 ("art" "species")
 ("arter" "species")
 ("i slekt med" "related")
 ("utvikle" "evolve")
 ("tilpasse" "adapt")
 ("fornærme" "offend")
 ("fornærmet" "offended")
 ("avstamning" "decent"))

(("slu" "sly")
 ("fjern" "distant")
 ("slektning" "relative")
 ("rødbrun" "reddish brown")
 ("jakt" "hunting")
 ("kobbel" "pack")
 ("forbudt" "banned")
 ("lurer" "tricks")
 ("nynære strøk" "urban areas")
 ("sykdom" "disease")
 ("rovdyr" "predator")
 ("truet" "endangered"))

(("sly" "slu")
 ("distant" "fjern")
 ("relative" "slektning")
 ("reddish brown" "rødbrun")
 ("hunting" "jakt")
 ("pack" "kobbel")
 ("banned" "forbudt")
 ("tricks" "lurer")
 ("urban areas" "nynære strøk")
 ("disease" "sykdom")
 ("predator" "rovdyr")
 ("endangered" "truet"))

  (("tellevitenskap" "statistikk")
   ("table" "tabell")
   ("figur med stolper" "søylediagram")
   ("middelverdi" "gjennomsnitt")
   ("1,2,3,..." "stigende rekkefølge")
   ("kjæledyr" "pet")
   ("kosesøt" "cuddly")
   ("søt" "sweet")
   ("å gå" "to walk")
   ("å børste" "to brush")
   ("å løpe" "to run")
   ("ta seg av" "take care of"))

  (("root" "rot")
   ("stilk" "stengel")
   ("leaf" "blad")
   ("flower" "blomst")
   ("seed" "frø")
   ("kjemisk formel for vann" "H2O")
   ("kjemisk formel for karbondioksid" "CO2")
   ("muslimenes religion" "islam")
   ("muslimenes profet" "Muhammed")
   ("muslimske kirken" "moskeen")
   ("community" "fellesskap")
   ("islamsk nyttår" "Ashura")
   ("irakisk by" "Kerbela")
   ("kjæledyr" "pet")
   ("kosesøt" "cuddly")
   ("søt" "sweet")
   ("å gå" "to walk")
   ("å børste" "to brush")
   ("å løpe" "to run")
   ("ta seg av" "take care of"))

  (("weight" "vekt")
   ("volume" "volum"))

  (("weight" "vekt")
   ("volume" "volum")
   ("materials" "materialer")
   ("mur under en bygning" "grunnmur")
   ("konstruksjonsdel av tømmer, jern, stål eller betong som bærer et golv og/el. tjener som feste for et tak" "bjelke")
   ("type norsk trekirker" "stavkirker")
   ("Middle Ages" "middelalderen")
   ("navn på et sted" "stedsnavn")
   ("gården der en prestefamilie bor" "prestegård")
   ("vei som pilegrimer går" "pilegrimsled")
   ("vokse opp" "grov up")
   ("kanskje" "maybe")
   ("øve" "practice")
   ("stylet" "styled")
   ("puddel" "poodle")
   ("fugler" "birds")
   ("flink" "clever"))

  (("the weekend" "helgen")
   ("protestants" "protestanter")
   ("catholics" "katolikker")
   ("holy (pl)" "hellige")
   ("historier om helgener" "helgenfortellinger")
   ("bishop" "biskop")
   ("raw material" "råmateriale")
   ("arbeide videre med" "bearbeide")
   ("oil" "olje")
   ("gasoline" "bensin")
   ("bensintype til Toyotaen" "diesel")
   ("fish oil" "fiskeolje")
   ("construction materials" "byggematerialer")
   ("lacqer" "lakk")
   ("china" "porselen")
   ("gruve der malmen blir brutt på jordoverflaten" "dagbrudd")
   ("busk" "bush")
   ("vokser" "grows")
   ("ikke rettferdig" "not fair")
   ("musefletter" "pigtails")
   ("stygg" "ugly")
   ("noe" "something")
   ("skuff" "drawer")
   ("vernebriller" "goggles")
   ("tablett" "tablet"))

  (("skill" "ferdighet")
   ("decimal digit" "desimaltall")
   ("weight" "vekt")
   ("volume" "volum")
   ("idol" "forbilde")
   ("cure" "helbrede")
   ("the golden rule" "den gylne regel")
   ("mercy" "barmhjertighet")
   ("charity" "nestekjærlighet")
   ("Unnskyld meg, kan du si meg...?" "Excuse me, can you tell me...?")
   ("Unnskyld, hvor kan jeg finne...?" "Excuse me, where can I find...?")
   ("Skynd deg!" "Hurry up!")
   ("Ha en god dag!" "Have a nice day!")
   ("etter" "after")
   ("tid til" "time to")
   ("må" "must"))


  (("detail" "detalj")
   ("cure" "helbrede")
   ("mercy" "barmhjertighet")
   ("samesløyd" "duodji")
   ("tradition" "tradisjon")
   ("presentation" "presentasjon")
   ("skoleklokke" "school bell")
   ("alarmklokke" "alarm clock")
   ("armbåndsur" "watch")
   ("butikk" "shop")
   ("liten kjerre" "trolley")
   ("dam" "pond"))

  (("tall med mer enn ett siffer" "flersifrede tall")
   ("rader og kolonner" "tabell")
   ("berette" "fortelle")
   ("stor gul sitrusfrukt" "appelsin")
   ("veldig gammel" "forhistorisk")
   ("tilintetgjort" "utryddet")
   ("fotgjengerfelt" "zebra crossing")
   ("buss" "bus")
   ("fortau" "pavement")
   ("trafikklys" "traffic lights")
   ("park" "park")
   ("bro" "bridge")
   ("kino" "cinema"))

  (("skrekkøgle" "dinosaur")
   ("forsteinet dyreavtrykk" "fossil")
   ("ganging" "multiplikasjon")
   ("summering" "addisjon")
   ("figur" "diagram")
   ("et tegn" "a sign")
   ("å være sammen med" "to be with")
   ("late som" "pretend")
   ("være sammen" "be together")
   ("burde" "ought to"))

  (("circumference" "omkrets")
   ("area" "areal")
   ("tallbasert" "digital")
   ("varme" "temperatur")
   ("sko til å løpe med" "")
   ("wallet" "lommebok")
   ("kjære" "dear")
   ("med" "with")
   ("dem" "them")
   ("tenke" "think")
   ("trenge" "need")
   ("pakke" "package")
   ("postkasse" "letterbox")
   ("nok en gang" "oncemore")
   ("hamselv" "himself"))

  (("der man lager juleting" "juleverksted")
   ("det julenissen spiser" "julegrøt")
   ("lager bakermester Harepus" "pepperkake" "pepperkaker")
   ("grantre med lys" "juletre")
   ("Glade Jul" "julesang")
   ("engelsk julesang" "Christmas carol")
   ("grøt" "porridge")
   ("pepperkake" "gingerbread")
   ("snømann" "snowman")
   ("snøfnugg" "snowflake"))

  (("iron" "jern")
   ("floating" "flytende")
   ("å oksidere" "å ruste")
   ("to swell" "å svelle")
   ("egg white" "eggehvite")
   ("to reflect" "å reflektere")
   ("jul" "Christmas")
   ("juletre" "Christmas tree")
   ("julenissen" "Santa Claus")
   ("tradisjoner" "traditions")
   ("tannlege" "dentist")
   ("åpne på vidt gap" "open wide up")
   ("tannkjøttet" "the gums")
   ("hulrom (pl)" "cavities")
   ("fylling" "filling")
   ("bor" "drill"))

  (("Norge" "Oslo" "Osjlo")
   ("Sverige" "Stockholm")
   ("Dannmark" "København")
   ("Finland" "Helsinki")
   ("Tyskland" "Berlin")
   ("Storbritannia" "London")
   ("Frankrike" "Paris")
   ("Italia" "Roma")
   ("Spania" "Madrid")
   ("Østerrike" "Wien")
   ("Russland" "Moskva")
   ("Island" "Reykjavik")
   ("Japan" "Tokyo")
   ("Kina" "Beijing")
   ("India" "New Dehli")
   ("USA" "Washington D.C." "Washington")
   ("Brasil" "Brasilia")
   ("Canada" "Ottawa")
   ("Australia" "Canberra")
   ("Nederland" "Amsterdam")
   ("Hellas" "Athen" "Aten")
   ("Belgia" "Brussel"))

  (("materiale" "stoff")
   ("property" "egenskap")
   ("condens" "fordampe")
   ("fordampe" "kondensere")
   ("er damp" "gass")
   ("chef" "kokk")
   ("storslagent" "flott")
   ("goal" "mål")
   ("fog" "tåke")
   ("jeg kan" "I can")
   ("jeg kan ikke" "I can')t")
 ("gåte" "riddle")
 ("utenfor" "outside")
 ("igjen" "again")
 ("(jeg/han/hun/den/det) var" "was")
 ("(du/vi/dere/de) var" "were")
 ("kan du ikke se" "can't you see"))

(("ganging" "multiplikasjon")
 ("deling" "divisjon")
 ("newspaper" "avis")
 ("report" "reportasje")
 ("utspørring" "intervju")
 ("med glede" "gjerne")
 ("redde" "hjelpe")
 ("wheel" "hjul")
 ("did" "gjorde")
 ("sulten" "hungry")
 ("vise" "show")
 ("hvordan" "how")
 ("trist" "sad")
 ("morsom" "funny")
 ("ser deg snart" "see you soon"))

(("GPSen"	 "posisjonssystemet")
 ("minus-siffre" "negative tall")
 ("å slette" 	 "å utrydde")
 ("å beskydde" 	 "å frede")	
 ("arv"		 "testamente")
 ("kirkegård"	 "graveyard")
 ("kosteskaft"	 "broomstick")
 ("spøkelse"	 "ghost")
 ("heks"	 "witch")
 ("vampyr" 	 "vampire"))

(("samtale" "dialog")
 ("bokstav for bokstav" "ordrett")
 ("svar" "replikk")
 ("bred bindestrek" "replikkstrek")
 ("evne til å tåle" "toleranse")
 ("styring" "politikk")
 ("vaktmester" "caretaker")
 ("paradis" "hopscotch")
 ("huske" "swing")
 ("pai" "pie"))

(("jeg er" "I am")
 ("du er" "you are")
 ("han/hun/det er" "he/she/it is")
 ("vi er" "we are")
 ("dere er" "you are")
 ("de er" "they are")
 ("tall" "sifre")
 ("pris" "verdi")
 ("innflytelse" "påvirkning")
 ("opptreden" "oppførsel"))

(("kjempestort hav" "verdenshav")
 ("verdenshav utenfor India" "Det indiske hav")
 ("verdenshav mellom Amerika og Europa (og Afrika)" "Atlanterhavet")
 ("verdenshav mellom Asia og Amerika" "Stillehavet")
 ("skap til å ha mat i" "matskap")
 ("sted der man jobber" "arbeidsplass")
 ("ville hatt" "krevd")
 ("ark i matte" "prosessnotat")
 ("deling" "divisjon")
 ("oppgaver i skriving" "tekstoppgaver"))

(("vokser, lever, råtner" "livssyklus")
 ("bo om vinteren" "overvintre")
 ("legge rogn" "gyte")
 ("fiskeegg" "rogn")
 ("fiskesperm" "melke")
 ("insektbarn" "larve")
 ("fugl som overvintrer i syden" "trekkfugl")
 ("trekkfugl på L" "linerle")
 ("som blir ett år" "ettårig")
 ("som blir flere år" "flerårig"))

(("Sopp på tre (flertall)" "kjuker")
 ("Bli til møkk" "råtne")
 ("Dødt dyr" "åtsel")
 ("Mikroorganisme" "bakterie")
 ("Dyr som spiser døde dyr" "åtseleter")
 ("Syn på menneskelivet" "livssyn")
 ("En type firkant" "parallellogram")
 ("90 graders" "rettvinklet")
 ("Fugleedderkopp" "tarantell")
 ("Klasse" "sjanger")
 ("Aktelse, ærbødighet, lydighet" "respekt"))

(("En som spiser døde dyr" "nedbryter")
 ("Sopp på tre (flertall)" "kjuker")
 ("Bli til møkk" "råtne")
 ("Dødt dyr" "åtsel")
 ("Mikroorganisme" "bakterie")
 ("Dyr som spiser døde dyr" "åtseleter")
 ("Syn på menneskelivet" "livssyn")
 ("En type firkant" "parallellogram")
 ("90 graders" "rettvinklet")
 ("Fugleedderkopp" "tarantell")
 ("Klasse" "sjanger")
 ("Aktelse, ærbødighet, lydighet" "respekt"))

(("stil" "skriveoppgave")
 ("skapende" "kreativ")
 ("tekstdel" "avsnitt")
 ("effekt" "virkemidler")
 ("merke" "kjennetegn")
 ("forklaring til oppgave" "eksempeltekst")
 ("opphav" "kilder")
 ("repetisjoner" "gjentakelser")
 ("jevnføring" "sammenlikning")
 ("virkning" "effekt"))

(("En kiste med gull" "skatt")
 ("Dødninghode" "hodeskalle")
 ("Redsel" "skrekk")
 ("Der man kan bade" "strand")
 ("Fra Spania" "spansk")
 ("I finansverdenen" "næringsliv")
 ("Frakte ut" "eksportere")
 ("Frakte inn" "importere")
 ("Plante som gror om våren" "vårblomst")
 ("Små gjess" "gåsunger")
 ("Tussilago farfara" "hestehov"))

(("Dagen før Jesus ble korsfestet" "skjærtorsdag")
 ("Dagen Jesus ble korsfestet" "langfredag")
 ("Dagen etter Jesus ble korsfestet" "påskeaften")
 ("Dagen etter Jesus sto opp fra de døde (to ord)" "første påskedag")
 ("Han som skrev om Snikker Andersen og skrev mange barnesanger" "Alf Prøysen")
 ("En beskrivelse av en persons liv" "biografi")
 ("Tidligste forsøk på noe man skal lage" "førsteutkast")
 ("Første siden eller omslaget på en bok" "forside")
 ("Sammenkomst i påsken" "påskesamling")
 ("Fridager i påsken" "påskeferie"))
