;;;; TODO: These helpers could be autogenerated from ld

;;; Users
;; Some convenient shortcuts to the user record
(defalias 'cram-user-id #'first)
(defalias 'cram-user-name #'second)
;; (defalias 'cram-user-rating #'third)
(cl-defun cram-user-rating (x) (third x))
(cl-defun cram-user-rating-e (x) (first (cram-user-rating x)))
(cl-defun cram-user-rating-d (x) (second (cram-user-rating x)))
(defalias 'cram-user-metadata #'last-elt)

(cl-defun cram-user-last-updated (user)
  (ld-get-metadatum :updated (cram-user-metadata user)))
;;(cram-user-last-updated (cram-db-get-user "Ludvik"))

;;; Problems
(defalias 'cram-problem-id #'first)
(defalias 'cram-problem-source-id #'second)
(defalias 'cram-problem-question #'third)
(defalias 'cram-problem-answer #'fourth)
(defalias 'cram-problem-picture #'fifth)
(defalias 'cram-problem-alternatives #'sixth)
(defalias 'cram-problem-hints #'seventh)
(defalias 'cram-problem-rating #'eighth)
(cl-defun cram-problem-rating-e (x) (first (cram-problem-rating x)))
(cl-defun cram-problem-rating-d (x) (second (cram-problem-rating x)))
(cl-defun cram-problem-metadata (x) (rest (ninth x)))
(cl-defun cram-problem-updated (x) (getf (cram-problem-metadata x) :updated))

;;; Matches
(defalias 'cram-match-id #'first)
(defalias 'cram-match-timestamp #'second)
(defalias 'cram-match-response #'third)
(defalias 'cram-match-time #'fourth)
(defalias 'cram-match-score #'fifth)
(defalias 'cram-match-user-id #'sixth)
(defalias 'cram-match-problem-id #'seventh)
(defalias 'cram-match-user-rating #'eighth)
(defalias 'cram-match-problem-rating #'ninth)

(provide 'cram-common)
